name: mockery
services:
  mockery:
    build: .
    container_name: mockery
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - C:\Users\daveh\source\repos\Mocks:/app/mocks
    environment:
      - MockRepository__Type=Local
      - MockRepository__LocalPath=/app
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=Mockery
