apiVersion: v2
name: mockery
description: A Helm chart for Mockery - REST API service for serving HTTP mock responses from Git repositories
type: application
version: 0.1.18
appVersion: "0.1.18"
keywords:
  - mockery
  - mock
  - api
  - testing
  - rest
  - git
home: https://github.com/busadave13/Mockery
sources:
  - https://github.com/busadave13/Mockery
icon: https://raw.githubusercontent.com/busadave13/Mockery/main/.github/assets/icon.png
maintainers:
  - name: Dave Harding
    url: https://github.com/busadave13
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/displayName: Mockery
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: GitHub Container Registry
