apiVersion: v2
name: mockery
description: A Helm chart for Mockery - REST API service for serving HTTP mock responses
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mockery
  - mock
  - api
  - testing
home: https://github.com/busadave13/Mockery
maintainers:
  - name: davhar
