apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
data: {}  # Throttling configuration
