{{- if .Values.secrets.gitAccessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: mockery
    release: {{ .Release.Name }}
type: Opaque
stringData:
  git-access-token: {{ .Values.secrets.gitAccessToken | quote }}
{{- end }}
